

--top selling products
select apl."ProductName" as Prd_name, sum("OrderQuantity") as total_units_sold
from adventureworks_product_lookup apl
join adventureworks_sales_data asd on asd."ProductKey" = apl."ProductKey"
group by 1
order by 2 desc
limit 15
-- Watch, Water Bottle and Patch Kit are the top-selling products,
-- with 7,967, 5,898 and 5,678 units sold respectively.
;

--top selling countries
select atl."Country" , sum(asd."OrderQuantity") as units_sold
from adventureworks_sales_data asd 
join adventureworks_territory_lookup atl 
on asd."TerritoryKey" = atl."SalesTerritoryKey"
group by 1
order by 2 desc
-- United States and Australia generated the highest sales volume.
;

--Top selling continents.
select atl."Continent" , sum(asd."OrderQuantity") as units_sold
from adventureworks_sales_data asd 
join adventureworks_territory_lookup atl 
on asd."TerritoryKey"  = atl."SalesTerritoryKey" 
group by atl."Continent" 
order by items_sold  desc
--North America generated most sales in units;

--Top customers by units bought
select concat(cl."FirstName", ' ', cl."LastName"), sum(asd."OrderQuantity") as total__units_purchased
from customer_lookup cl 
join adventureworks_sales_data asd 
on cl."CustomerKey" = asd."CustomerKey"
group by 1
order by 2 desc
limit 15
--J.Simmons and F.Barnes purchased most units (106)
;

--Top customers by revenue generated
select concat(cl."FirstName", ' ', cl."LastName"), sum(asd."OrderQuantity") as total_units_purchased, 
round(sum(asd."OrderQuantity" * apl."ProductPrice")::numeric,2) as revenue_brought
from customer_lookup cl 
join adventureworks_sales_data asd 
on cl."CustomerKey" = asd."CustomerKey" 
join adventureworks_product_lookup apl 
on apl."ProductKey" = asd."ProductKey" 
group by 1
order by revenue_brought desc
limit 15
--Most revenue generated by J.turner
;

--Top selling categories
select apcl."CategoryName" , sum(asd."OrderQuantity") as total_units_sales, 
round(sum(asd."OrderQuantity" * apl."ProductPrice")::numeric,0) as total_revenue,
round(sum(asd."OrderQuantity"  * apl."ProductCost")::numeric,0) as total_cost,
round(sum(asd."OrderQuantity" * apl."ProductPrice")::numeric -
sum(asd."OrderQuantity"  * apl."ProductCost")::numeric,1) as profit
from adventureworks_sales_data asd 
join adventureworks_product_lookup apl 
on apl."ProductKey" =asd."ProductKey" 
join adventureworks_product_subcategories_lookup apsl 
on apsl."ProductSubcategoryKey"  = apl."ProductSubcategoryKey"  
join adventureworks_product_categories_lookup apcl 
on apsl."ProductCategoryKey"  = apcl."ProductCategoryKey"
group by apcl."CategoryName"
order by total_revenue desc
-- -- Accessories generated the highest sales volume in units sold.
-- Bikes generated the highest revenue despite significantly lower unit sales.
;